#!/bin/bash

DATADIR="/home/eth/data"
geth \
    --datadir "$DATADIR" \
    --networkid 15 \
    --nodiscover \
    --allow-insecure-unlock \
    --http \
    --http.port "$PORT" \
    --port "30303" \
    --http.vhosts "*" \
    --http.corsdomain "*" \
    --http.api eth,web3,personal,net \
    --http.addr "0.0.0.0" \
    --nat "any" \
    --maxpeers 0 \
    --unlock "0x54b16d9f3D83c4261e60c98253F60943aD487a7d" \
    --password "password.sec" 

